pipeline {
    agent {
      label 'aws'
    }
    
    environment {
        // Define environment variables
        DOCKER_REGISTRY = 'docker.io'
        DOCKER_IMAGE_NAME = 'imageimpressario/echoserver'
        GIT_REPO_URL = 'https://github.com/yogeshraj-au/echoserver.git'
        DOCKERFILE_PATH = 'Dockerfile'
        BASE_VERSION = '1.0'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the Git repository
                git branch: 'main', url: env.GIT_REPO_URL
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    // Generate semantic version and tag the Docker image
                    def version = "${env.BASE_VERSION}.${env.BUILD_NUMBER}"
                    env.TAGGED_IMAGE = "${env.DOCKER_IMAGE_NAME}:${version}"
                    
                    docker.build(env.TAGGED_IMAGE, "--file ${env.DOCKERFILE_PATH} .")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', passwordVariable: 'DOCKER_HUB_PASSWORD', usernameVariable: 'DOCKER_HUB_USERNAME')]) {
                    script {
                        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                            docker.image(env.TAGGED_IMAGE).push()
                        }
                    }
                }
            }
        }
    }
    
    post {
        success {
            echo "Docker image build and push successful"
        }
        failure {
            echo "Docker image build or push failed"
        }
    }
}
